name: Headless

on:

  workflow_dispatch:
  push:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write  # for actions/upload-release-asset to upload release asset
    runs-on: ubuntu-latest
    env:
      RELEASE_NAME: RGFW-dev_headless_${{ matrix.ARCH_NAME }}

    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Setup Release Version
      run: |
        echo "RELEASE_NAME=RGFW-${{ github.event.release.tag_name }}_headless_${{ matrix.ARCH_NAME }}" >> $GITHUB_ENV
      shell: bash
      if: github.event_name == 'release' && github.event.action == 'published'

    - name: Generate Artifacts
      run: |
          echo starting
          cp RGFW.h RGFW-${{ github.event.release.tag_name }}.h

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: RGFW${{ github.event.release.tag_name }}.h
        path: RGFW-${{ github.event.release.tag_name }}.h

    - name: Upload Artifact to Release
      uses: softprops/action-gh-release@v1
      with:
        files: RGFW$-{{ github.event.release.tag_name }}.h
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name == 'release' && github.event.action == 'published'
